### ISSUE TITLE
Experiment dependencies

### ISSUE THREAD

**Issue by tsloughter** [lasp-lang/lasp#183]
The experiments seem closely entwined with the core code. This means dependencies like `erlcloud` can not be simply moved to a profile because it is needed to be started by the app.

I'm not sure how you actually run the experiments but it seems experiments warrant a separate app that depends on lasp and that app then handles all the setup/upload/etc that is currently embedded in the main lasp code base.

**Comment by cmeiklejohn** [comment]
You're probably right, but this isn't something that we're going to be able to fix until after the end of the year because we're in the middle of running experiments for a report due December 31.  Until then, it's going to have to stay the way it is.

Ideally, after December 31 we'll move the Sprinter/Nuages code out to it's own repository, which will bring the erlcloud and assorted dependencies with it.

**Comment by tsloughter** [comment]
Ok cool. Do you want to leave this open so no one else asks the same question or should I close it?

**Comment by cmeiklejohn** [comment]
Close it for now, we know this work is necessary and will address it moving
forward as part of the Lasp work in 2017.
