### ISSUE TITLE
Lasp.stream/2 callbacks are not invoked when state_orset changes

### ISSUE THREAD

**Issue by rosacris** [lasp-lang/lasp#261]
I have found a situation where Lasp.stream/2 callbacks are not invoked even if the state_orset is properly replicated on each node of the cluster.
Here are the steps to reproduce it:

1- start two nodes, each with a gen_server that declares a state_orset with the same id on init/1
2- then both call lasp.stream/2 on that state_orset to register a callback function
3- connect both nodes using partisan_peer_service.join/1
4- add/remove elements to/from the state_orset. The callback functions are not called, however the state_orset is properly replicated on both nodes

Now, if I first join the nodes, and then delcare and register the callbacks, then they are properly called when elements are added/removed

**Comment by cmeiklejohn** [comment]
My suspicion here is that it has to do with not being able to register the callback before the variable is declared at a given node: by joining first, you are ensuring that the declaration of the variable is performed on all nodes before starting the callback registration.  

I'm curious, if you reorder the join and declaration, I'd assume that *one* of the callbacks would at least work, and the node that didn't issue the declare wouldn't.  This would confirm that the issue is that the callback can not be registered before the declare succeeds.

**Comment by rosacris** [comment]
I've found an error in my test case (the init/1 function was not being called at all).
:lasp.stream/2 is working as expected, with either the join before or after the stream call.
I'm sorry for the noise.
